{% set name = "nose_xunitmp" %}
{% set version = "0.4.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c2df72f4760751d30153d473822aabf1a7c3d462f664aa7f7fdb8dc626dc7c40

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
  - pip
  - python
  run:
  - nose
  - python
  - setuptools

test:
  imports:
    - nose_xunitmp

about:
  home: https://github.com/Ignas/nose_xunitmp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Nose plugin that makes xunit xml reports work when running tests on more than one cpu.
  dev_url: https://github.com/Ignas/nose_xunitmp

extra:
  recipe-maintainers:
  - andreyz4k
