travis:
  secure:
    BINSTAR_TOKEN: scVUr6lwmxrqmV8b8z90Gu4vLLX2zyEEOMh0zGtVRTlB0wzJ2cgB69pru+GZfLQ/Q/wI1T2ZZ8OIx20//YNfJb48NZOIaUgLAPht0dvZEFehDibEBfWc+3+krvdn9dcVQf3ygBG1ekYekFdVa1eYz3TXD3Y8BsD8Auf11NiOTQDJi64fzPNUP7gMgnK9R0hFq0lp1HN3tdjhdefNVAmtUX3Pzg4keSRCvQp7sdhZ+h53s13JG7Kq3rKb1UKFvP45SqcdmAvX05OQ2sYJ4+zkre99sr26oT6EgLIInJy03FXAcBK8OYAwKtfoCSxW8XMrsZi6C5kJhyiJW7rpVk0YWpNYmOvpQG8LEFzRHL0CxGTthlAFmFTn1yPwOkBJmEGSsBihue9gjdrwn/ckOfVlFThWK6JETI3o9hZvcyLV+VqrB9xUfwKd9uyQBce0lrmc0z1/gVPQI74jY5CodUtjBaJuuVs+YNFQTXkTec+Rf8nr9bz990NpF4YpoCDTLCSaNSWNBWys8uT7TxUTZ1YX1ZFrCqOVfgMFhc2TsqOgSRIWPNHIsQ/99aCTc8xpeKecS19DjvxcwKzlCJBMPOr6Xw1NmheIMRUCnzgsj5+vXQoYQscVeYbskDmAux+bgYl0cypLBeGvZkwVkLdj3VPXsgzDr4qBvLWyL//pfDLUBds=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
